In [1]:
import numpy as np
import pandas as pd

In [2]:
z = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(z[0:2, 0:1] ** 3)
#print(np.arange(1,10,2))
#z.shape

[[ 1]
 [64]]


In [3]:
z[1,:] = 1
z[1, 1] = 9
z[2,-1] = -1
print(z)

[[ 1  2  3]
 [ 1  9  1]
 [ 7  8 -1]]


In [4]:
x = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(x)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [5]:
x = np.full((4,2),1)
y = np.full((3,3),0)
#np.stack((x,y), axis = 1)
print(x)
x = x.reshape((1,8))
print(x)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[1 1 1 1 1 1 1 1]]


In [6]:
import math
x = np.random.randint(1,9,3)
print(x)
#np.random.seed(1)
y = np.random.randint(1,9)
print(y)

[4 8 6]
8


In [7]:
#PANDAS

In [8]:
import pandas as pd

In [9]:
data = {
    "Gojo":np.random.randint(10,100,4),
    "Zenitsu":np.random.randint(10,100,4),
    "Tanjiro":np.random.randint(10,100,4),
    "Itachi":np.random.randint(10,100,4)
}

In [10]:
user_data = pd.DataFrame(data)
print(user_data)

   Gojo  Zenitsu  Tanjiro  Itachi
0    75       18       95      61
1    99       40       33      58
2    66       63       29      15
3    70       16       63      65


In [11]:
user_data.head()

Gojo  Zenitsu  Tanjiro  Itachi
0    75       18       95      61
1    99       40       33      58
2    66       63       29      15
3    70       16       63      65

In [12]:
user_data.to_csv("temp.csv",index=False)
pd.read_csv("temp.csv")

Gojo  Zenitsu  Tanjiro  Itachi
0    75       18       95      61
1    99       40       33      58
2    66       63       29      15
3    70       16       63      65

In [13]:
#SCIKIT-LEARN

In [14]:
from sklearn.datasets import make_regression

In [16]:
X,y = make_regression()

In [17]:
ipl_data = {'team': ['CSK', 'RCB', 'KKR'], 'wins': ['4', '0', '2'], 'rank': ['1', '2', '3']}
data = pd.DataFrame(ipl_data)

In [50]:
z = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13],[14,15,16]])
z[1:5:2,0:2:1]

array([[ 4,  5],
       [11, 12]])

In [8]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]]])
b = a[1:2,1:2,1:2]
print(b)

[[[5]]]


In [8]:
a = {'name':['x','y','z'], 'age':[1,2,3]}
data = pd.DataFrame(a)
print(dtpye(a))

NameError: name 'dtpye' is not defined